frontend:
  image: erikap/nginx-ember-proxy
  links:
    - identifier:backend
  ports:
    - "80:80"
  volumes:
    - ./smart-home-frontend/dist:/usr/share/nginx/html
identifier:
  image: semtech/mu-identifier:1.0.0
  links:
    - dispatcher:dispatcher
  # ports:
  #   - "80:80"
dispatcher:
  image: semtech/mu-dispatcher:1.0.1
  links:
    - resource:resource
    - apiai:apiai
  volumes:
    - ./config:/config
db:
  image: tenforce/virtuoso:1.0.0-virtuoso7.2.4
  environment:
    SPARQL_UPDATE: "true"
  ports:
    - "8890:8890"
  volumes:
    - ./virtuoso:/data
resource:
  image: semtech/mu-cl-resources:1.12.4
  links:
    - db:database
  volumes:
    - ./config/resources:/config
apiai:
  image: erikap/mu-apiai-thermostat-service
  environment:
    APIAI_ACCESS_TOKEN: "asecrettoken"
  links:
    - db:database

